kind: "API"
version: "1.0"
metadata:
  envTypes: ["dev", "stage", "prod", "rde"] # Applies across your environments
data:
  allowedClientIDs:
    author:
      - "68d455500fa04f2cbac4693108df242f"
      - "f75930e43f7f41ce8d7e58474e034740"
